package:
  name: coinbot
  version: latest

source:
  git_rev: master
  git_url: git@github.com:JoonasMelin/coinbot.git

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home:
  license:
  license_file:
